-- =============================================================================
-- PROYECTO INTEGRADOR: TurismoUQ
-- ARCHIVO: 02_ddl_tablas.sql
-- DESCRIPCIÓN: Script DDL completo para la creación de las 14 entidades base
--              con restricciones PK, FK, CHECK, NOT NULL, UNIQUE y Tablespaces.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. LIMPIEZA DE TABLAS PREVIAS (DROP INVERSO A LAS DEPENDENCIAS)
-- -----------------------------------------------------------------------------
BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables WHERE table_name IN (
            'RESENA', 'RESERVA_SERVICIO', 'SERVICIO', 'PAGO', 
            'RESERVA_HABITACION', 'RESERVA', 'CLIENTE', 'TARIFA', 
            'TEMPORADA', 'HABITACION', 'ALOJAMIENTO', 'TIPO_ALOJAMIENTO', 
            'MUNICIPIO', 'USUARIO_SISTEMA'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- -----------------------------------------------------------------------------
-- 1. TABLA: MUNICIPIO
-- -----------------------------------------------------------------------------
CREATE TABLE municipio (
    id_municipio     NUMBER(4) GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR2(60) NOT NULL,
    indicativo_post  VARCHAR2(10),
    CONSTRAINT pk_municipio PRIMARY KEY (id_municipio),
    CONSTRAINT uk_municipio_nombre UNIQUE (nombre)
);

-- -----------------------------------------------------------------------------
-- 2. TABLA: TIPO_ALOJAMIENTO
-- -----------------------------------------------------------------------------
CREATE TABLE tipo_alojamiento (
    id_tipo_alojamiento NUMBER(3) GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR2(50) NOT NULL,
    descripcion         VARCHAR2(250),
    CONSTRAINT pk_tipo_alojamiento PRIMARY KEY (id_tipo_alojamiento),
    CONSTRAINT uk_tipo_alojamiento_nombre UNIQUE (nombre)
);

-- -----------------------------------------------------------------------------
-- 3. TABLA: ALOJAMIENTO
-- -----------------------------------------------------------------------------
CREATE TABLE alojamiento (
    id_alojamiento      NUMBER(6) GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR2(100) NOT NULL,
    direccion           VARCHAR2(150) NOT NULL,
    telefono            VARCHAR2(20),
    correo              VARCHAR2(100),
    id_municipio        NUMBER(4) NOT NULL,
    id_tipo_alojamiento NUMBER(3) NOT NULL,
    CONSTRAINT pk_alojamiento PRIMARY KEY (id_alojamiento),
    CONSTRAINT fk_alojamiento_municipio FOREIGN KEY (id_municipio) 
        REFERENCES municipio(id_municipio),
    CONSTRAINT fk_alojamiento_tipo FOREIGN KEY (id_tipo_alojamiento) 
        REFERENCES tipo_alojamiento(id_tipo_alojamiento)
);

-- -----------------------------------------------------------------------------
-- 4. TABLA: HABITACION
-- -----------------------------------------------------------------------------
CREATE TABLE habitacion (
    id_habitacion       NUMBER(8) GENERATED BY DEFAULT AS IDENTITY,
    numero_habitacion   VARCHAR2(10) NOT NULL,
    tipo                VARCHAR2(30) NOT NULL,
    capacidad           NUMBER(2) NOT NULL,
    descripcion         VARCHAR2(200),
    id_alojamiento      NUMBER(6) NOT NULL,
    CONSTRAINT pk_habitacion PRIMARY KEY (id_habitacion),
    CONSTRAINT fk_habitacion_alojamiento FOREIGN KEY (id_alojamiento) 
        REFERENCES alojamiento(id_alojamiento) ON DELETE CASCADE,
    CONSTRAINT chk_habitacion_capacidad CHECK (capacidad > 0)
);

-- -----------------------------------------------------------------------------
-- 5. TABLA: TEMPORADA
-- -----------------------------------------------------------------------------
CREATE TABLE temporada (
    id_temporada        NUMBER(4) GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR2(50) NOT NULL,
    fecha_inicio        DATE NOT NULL,
    fecha_fin           DATE NOT NULL,
    tipo_temporada      VARCHAR2(10) DEFAULT 'BAJA' NOT NULL,
    CONSTRAINT pk_temporada PRIMARY KEY (id_temporada),
    CONSTRAINT chk_temporada_fechas CHECK (fecha_fin > fecha_inicio),
    CONSTRAINT chk_tipo_temporada CHECK (tipo_temporada IN ('ALTA', 'MEDIA', 'BAJA'))
);

-- -----------------------------------------------------------------------------
-- 6. TABLA: TARIFA
-- -----------------------------------------------------------------------------
CREATE TABLE tarifa (
    id_tarifa           NUMBER(8) GENERATED BY DEFAULT AS IDENTITY,
    id_habitacion       NUMBER(8) NOT NULL,
    id_temporada        NUMBER(4) NOT NULL,
    precio_noche        NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_tarifa PRIMARY KEY (id_tarifa),
    CONSTRAINT fk_tarifa_habitacion FOREIGN KEY (id_habitacion) 
        REFERENCES habitacion(id_habitacion) ON DELETE CASCADE,
    CONSTRAINT fk_tarifa_temporada FOREIGN KEY (id_temporada) 
        REFERENCES temporada(id_temporada),
    CONSTRAINT uk_tarifa_hab_temp UNIQUE (id_habitacion, id_temporada),
    CONSTRAINT chk_tarifa_precio CHECK (precio_noche > 0)
);

-- -----------------------------------------------------------------------------
-- 7. TABLA: CLIENTE
-- -----------------------------------------------------------------------------
CREATE TABLE cliente (
    id_cliente          NUMBER(8) GENERATED BY DEFAULT AS IDENTITY,
    num_documento       VARCHAR2(20) NOT NULL,
    tipo_documento      VARCHAR2(10) NOT NULL,
    nombres             VARCHAR2(60) NOT NULL,
    apellidos           VARCHAR2(60) NOT NULL,
    correo              VARCHAR2(100) NOT NULL,
    telefono            VARCHAR2(20),
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uk_cliente_documento UNIQUE (num_documento),
    CONSTRAINT uk_cliente_correo UNIQUE (correo),
    CONSTRAINT chk_cliente_doc_tipo CHECK (tipo_documento IN ('CC', 'CE', 'PASAPORTE', 'TI'))
);

-- -----------------------------------------------------------------------------
-- 8. TABLA: RESERVA (Ubicada en TABLESPACE TS_HISTORICO_RESERVAS)
-- -----------------------------------------------------------------------------
CREATE TABLE reserva (
    id_reserva          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    fecha_reserva       DATE DEFAULT SYSDATE NOT NULL,
    fecha_checkin       DATE NOT NULL,
    fecha_checkout      DATE NOT NULL,
    estado              VARCHAR2(20) DEFAULT 'CONFIRMADA' NOT NULL,
    total               NUMBER(12,2) DEFAULT 0 NOT NULL,
    id_cliente          NUMBER(8) NOT NULL,
    CONSTRAINT pk_reserva PRIMARY KEY (id_reserva),
    CONSTRAINT fk_reserva_cliente FOREIGN KEY (id_cliente) 
        REFERENCES cliente(id_cliente),
    CONSTRAINT chk_reserva_fechas CHECK (fecha_checkout > fecha_checkin),
    CONSTRAINT chk_reserva_estado CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'FINALIZADA'))
) TABLESPACE ts_historico_reservas;

-- -----------------------------------------------------------------------------
-- 9. TABLA: RESERVA_HABITACION (Relación Muchos a Muchos: Reserva - Habitación)
-- -----------------------------------------------------------------------------
CREATE TABLE reserva_habitacion (
    id_reserva          NUMBER(10) NOT NULL,
    id_habitacion       NUMBER(8) NOT NULL,
    precio_noches_total NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_reserva_habitacion PRIMARY KEY (id_reserva, id_habitacion),
    CONSTRAINT fk_reshab_reserva FOREIGN KEY (id_reserva) 
        REFERENCES reserva(id_reserva) ON DELETE CASCADE,
    CONSTRAINT fk_reshab_habitacion FOREIGN KEY (id_habitacion) 
        REFERENCES habitacion(id_habitacion),
    CONSTRAINT chk_reshab_precio CHECK (precio_noches_total >= 0)
) TABLESPACE ts_historico_reservas;

-- -----------------------------------------------------------------------------
-- 10. TABLA: PAGO
-- -----------------------------------------------------------------------------
CREATE TABLE pago (
    id_pago             NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    fecha_pago          DATE DEFAULT SYSDATE NOT NULL,
    monto               NUMBER(10,2) NOT NULL,
    metodo_pago         VARCHAR2(30) NOT NULL,
    id_reserva          NUMBER(10) NOT NULL,
    CONSTRAINT pk_pago PRIMARY KEY (id_pago),
    CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva) 
        REFERENCES reserva(id_reserva) ON DELETE CASCADE,
    CONSTRAINT chk_pago_monto CHECK (monto > 0),
    CONSTRAINT chk_pago_metodo CHECK (metodo_pago IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'PSE'))
);

-- -----------------------------------------------------------------------------
-- 11. TABLA: SERVICIO
-- -----------------------------------------------------------------------------
CREATE TABLE servicio (
    id_servicio         NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR2(80) NOT NULL,
    descripcion         VARCHAR2(200),
    precio_base         NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_servicio PRIMARY KEY (id_servicio),
    CONSTRAINT uk_servicio_nombre UNIQUE (nombre),
    CONSTRAINT chk_servicio_precio CHECK (precio_base >= 0)
);

-- -----------------------------------------------------------------------------
-- 12. TABLA: RESERVA_SERVICIO (Ubicada en TABLESPACE TS_HISTORICO_RESERVAS)
-- -----------------------------------------------------------------------------
CREATE TABLE reserva_servicio (
    id_reserva_servicio NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_reserva          NUMBER(10) NOT NULL,
    id_servicio         NUMBER(5) NOT NULL,
    cantidad            NUMBER(3) DEFAULT 1 NOT NULL,
    precio_unitario     NUMBER(10,2) NOT NULL,
    subtotal            NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_reserva_servicio PRIMARY KEY (id_reserva_servicio),
    CONSTRAINT fk_resserv_reserva FOREIGN KEY (id_reserva) 
        REFERENCES reserva(id_reserva) ON DELETE CASCADE,
    CONSTRAINT fk_resserv_servicio FOREIGN KEY (id_servicio) 
        REFERENCES servicio(id_servicio),
    CONSTRAINT chk_resserv_cantidad CHECK (cantidad > 0)
) TABLESPACE ts_historico_reservas;

-- -----------------------------------------------------------------------------
-- 13. TABLA: RESENA
-- -----------------------------------------------------------------------------
CREATE TABLE resena (
    id_resena           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    calificacion        NUMBER(1) NOT NULL,
    comentario          VARCHAR2(500),
    fecha_resena        DATE DEFAULT SYSDATE NOT NULL,
    id_reserva          NUMBER(10) NOT NULL,
    CONSTRAINT pk_resena PRIMARY KEY (id_resena),
    CONSTRAINT uk_resena_reserva UNIQUE (id_reserva),
    CONSTRAINT fk_resena_reserva FOREIGN KEY (id_reserva) 
        REFERENCES reserva(id_reserva) ON DELETE CASCADE,
    CONSTRAINT chk_resena_calificacion CHECK (calificacion BETWEEN 1 AND 5)
);

-- -----------------------------------------------------------------------------
-- 14. TABLA: USUARIO_SISTEMA
-- -----------------------------------------------------------------------------
CREATE TABLE usuario_sistema (
    id_usuario          NUMBER(6) GENERATED BY DEFAULT AS IDENTITY,
    username            VARCHAR2(50) NOT NULL,
    password_hash       VARCHAR2(256) NOT NULL,
    rol                 VARCHAR2(30) NOT NULL,
    id_alojamiento      NUMBER(6),
    CONSTRAINT pk_usuario_sistema PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_username UNIQUE (username),
    CONSTRAINT fk_usuario_alojamiento FOREIGN KEY (id_alojamiento) 
        REFERENCES alojamiento(id_alojamiento) ON DELETE SET NULL,
    CONSTRAINT chk_usuario_rol CHECK (rol IN ('RECEPCION', 'ADMIN_ALOJAMIENTO', 'GERENTE', 'AUDITOR'))
);