-- =============================================================================
-- PROYECTO INTEGRADOR: TurismoUQ
-- ARCHIVO: 02_ddl_tablas.sql
-- DESCRIPCIÓN: Script DDL adaptado 100% al Diagrama ER entregado.
-- =============================================================================

BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables WHERE table_name IN (
            'RESENA', 'RESERVA_SERVICIO', 'SERVICIO', 'PAGO', 
            'RESERVA_HABITACION', 'RESERVA', 'CLIENTE', 'TARIFA', 
            'TEMPORADA', 'HABITACION', 'ALOJAMIENTO', 'TIPO_ALOJAMIENTO', 
            'MUNICIPIO', 'USUARIO_SISTEMA'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- 1. MUNICIPIO
CREATE TABLE municipio (
    id_municipio     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR2(100) NOT NULL,
    descripcion      VARCHAR2(250),
    CONSTRAINT pk_municipio PRIMARY KEY (id_municipio)
);

-- 2. TIPO_ALOJAMIENTO
CREATE TABLE tipo_alojamiento (
    id_tipo_alojamiento NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_tipo_alojamiento PRIMARY KEY (id_tipo_alojamiento)
);

-- 3. ALOJAMIENTO
CREATE TABLE alojamiento (
    id_alojamiento      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_municipio        NUMBER NOT NULL,
    id_tipo_alojamiento NUMBER NOT NULL,
    nombre              VARCHAR2(150) NOT NULL,
    direccion           VARCHAR2(200) NOT NULL,
    telefono            VARCHAR2(30),
    CONSTRAINT pk_alojamiento PRIMARY KEY (id_alojamiento),
    CONSTRAINT fk_aloj_municipio FOREIGN KEY (id_municipio) REFERENCES municipio(id_municipio),
    CONSTRAINT fk_aloj_tipo FOREIGN KEY (id_tipo_alojamiento) REFERENCES tipo_alojamiento(id_tipo_alojamiento)
);

-- 4. USUARIO_SISTEMA
CREATE TABLE usuario_sistema (
    id_usuario          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_alojamiento      NUMBER,
    username            VARCHAR2(50) NOT NULL,
    password_hash       VARCHAR2(256) NOT NULL,
    rol                 VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_usuario_sistema PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_username UNIQUE (username),
    CONSTRAINT fk_usuario_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES alojamiento(id_alojamiento)
);

-- 5. HABITACION
CREATE TABLE habitacion (
    id_habitacion       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_alojamiento      NUMBER NOT NULL,
    numero              VARCHAR2(20) NOT NULL,
    capacidad           NUMBER NOT NULL,
    CONSTRAINT pk_habitacion PRIMARY KEY (id_habitacion),
    CONSTRAINT fk_hab_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES alojamiento(id_alojamiento) ON DELETE CASCADE
);

-- 6. TEMPORADA
CREATE TABLE temporada (
    id_temporada        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR2(100) NOT NULL,
    fecha_inicio        DATE NOT NULL,
    fecha_fin           DATE NOT NULL,
    CONSTRAINT pk_temporada PRIMARY KEY (id_temporada)
);

-- 7. TARIFA
CREATE TABLE tarifa (
    id_tarifa           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_habitacion       NUMBER NOT NULL,
    id_temporada        NUMBER NOT NULL,
    valor_noche         NUMBER(12,2) NOT NULL,
    CONSTRAINT pk_tarifa PRIMARY KEY (id_tarifa),
    CONSTRAINT fk_tarifa_habitacion FOREIGN KEY (id_habitacion) REFERENCES habitacion(id_habitacion) ON DELETE CASCADE,
    CONSTRAINT fk_tarifa_temporada FOREIGN KEY (id_temporada) REFERENCES temporada(id_temporada)
);

-- 8. CLIENTE
CREATE TABLE cliente (
    id_cliente          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo_identificacion VARCHAR2(20) NOT NULL,
    identificacion      VARCHAR2(30) NOT NULL,
    nombre_completo     VARCHAR2(150) NOT NULL,
    email               VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uk_cliente_identificacion UNIQUE (identificacion),
    CONSTRAINT uk_cliente_email UNIQUE (email)
);

-- 9. SERVICIO
CREATE TABLE servicio (
    id_servicio         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_alojamiento      NUMBER NOT NULL,
    nombre              VARCHAR2(100) NOT NULL,
    precio_unitario     NUMBER(12,2) NOT NULL,
    CONSTRAINT pk_servicio PRIMARY KEY (id_servicio),
    CONSTRAINT fk_servicio_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES alojamiento(id_alojamiento) ON DELETE CASCADE
);

-- 10. RESERVA (TABLESPACE TS_HISTORICO_RESERVAS)
CREATE TABLE reserva (
    id_reserva          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente          NUMBER NOT NULL,
    fecha_creacion      DATE DEFAULT SYSDATE NOT NULL,
    estado              VARCHAR2(30) NOT NULL,
    CONSTRAINT pk_reserva PRIMARY KEY (id_reserva),
    CONSTRAINT fk_reserva_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
) TABLESPACE ts_historico_reservas;

-- 11. RESERVA_HABITACION (TABLESPACE TS_HISTORICO_RESERVAS)
CREATE TABLE reserva_habitacion (
    id_reserva_habitacion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_reserva            NUMBER NOT NULL,
    id_habitacion         NUMBER NOT NULL,
    fecha_checkin         DATE NOT NULL,
    fecha_checkout        DATE NOT NULL,
    subtotal_calculado    NUMBER(12,2) NOT NULL,
    CONSTRAINT pk_reserva_habitacion PRIMARY KEY (id_reserva_habitacion),
    CONSTRAINT fk_reshab_reserva FOREIGN KEY (id_reserva) REFERENCES reserva(id_reserva) ON DELETE CASCADE,
    CONSTRAINT fk_reshab_habitacion FOREIGN KEY (id_habitacion) REFERENCES habitacion(id_habitacion)
) TABLESPACE ts_historico_reservas;

-- 12. RESERVA_SERVICIO (TABLESPACE TS_HISTORICO_RESERVAS)
CREATE TABLE reserva_servicio (
    id_reserva_servicio NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_reserva          NUMBER NOT NULL,
    id_servicio         NUMBER NOT NULL,
    cantidad            NUMBER NOT NULL,
    fecha_consumo       DATE NOT NULL,
    subtotal            NUMBER(12,2) NOT NULL,
    CONSTRAINT pk_reserva_servicio PRIMARY KEY (id_reserva_servicio),
    CONSTRAINT fk_resserv_reserva FOREIGN KEY (id_reserva) REFERENCES reserva(id_reserva) ON DELETE CASCADE,
    CONSTRAINT fk_resserv_servicio FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio)
) TABLESPACE ts_historico_reservas;

-- 13. PAGO
CREATE TABLE pago (
    id_pago             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_reserva          NUMBER NOT NULL,
    fecha_transaccion   DATE DEFAULT SYSDATE NOT NULL,
    monto               NUMBER(12,2) NOT NULL,
    metodo              VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_pago PRIMARY KEY (id_pago),
    CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva) REFERENCES reserva(id_reserva) ON DELETE CASCADE
);

-- 14. RESENA
CREATE TABLE resena (
    id_resena           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente          NUMBER NOT NULL,
    id_alojamiento      NUMBER NOT NULL,
    calificacion        NUMBER(1) NOT NULL,
    comentario          VARCHAR2(500),
    fecha_publicacion   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_resena PRIMARY KEY (id_resena),
    CONSTRAINT fk_resena_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT fk_resena_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES alojamiento(id_alojamiento),
    CONSTRAINT chk_resena_calificacion CHECK (calificacion BETWEEN 1 AND 5)
);